version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
    - "7000:15672"
    - "5672:5672"
    hostname: rabbitmq
  discovery:
    build:
      context: ./discovery_server
    ports:
    - "5000:5000"
    hostname: discovery_server