version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "7000:15672"
      - "5672:5672"
    hostname: rabbitmq
    
  discovery:
    build:
      context: ./discoveryservice
    depends_on:
      - "rabbitmq"  
    hostname: discovery
    
  gateway:
    build:
      context: ./api_gateway
    ports:
      - "7001:8080"  
    depends_on:
      - "discovery"    
    hostname: gateway
    
  client:
    build:
      context: ./client
    ports:
      - "7002:80"
    depends_on:
      - "discovery"
    hostname: client
    
  sales:
    build:
      context: ./salesmanagement
    depends_on:
      - "discovery"
    hostname: sales
    
  notification:
    build:
      context: ./notificationservice
    depends_on:
      - "discovery"
    hostname: notification