version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "7000:15672"
      - "5672:5672"
    hostname: rabbitmq
    
  discovery:
    build:
      context: ./discoveryservice
    depends_on:
      - "rabbitmq"  
    hostname: discovery