version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
    - "7000:15672"
    - "5672:5672"
    hostname: rabbitmq
  client:
    build:
      context: ./client
    ports:
    - "7001:80"
    hostname: client