version: "3"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    ports:
      - "7000:15672"
      - "5672:5672"
    hostname: rabbitmq
    
  gateway:
    build:
      context: ./api_gateway
    ports:
      - "7001:8080"  
    depends_on:
      - "rabbitmq"    
    hostname: gateway
    
  client:
    build:
      context: ./client
    ports:
      - "7002:80"
    depends_on:
      - "rabbitmq"
    hostname: client
    
  sales:
    build:
      context: ./salesmanagement
    depends_on:
      - "rabbitmq"
    hostname: sales
    
  warehouse:
    build:
      context: ./warehousemanagement
    depends_on:
      - "rabbitmq"
    hostname: warehouse
    
  customer:
    build:
      context: ./customermanagement
    depends_on:
      - "rabbitmq"
    hostname: customer
    
  notification:
    build:
      context: ./notificationservice
    depends_on:
      - "rabbitmq"
    hostname: notification
  
  reminder:
    build:
      context: ./reminderservice
    depends_on:
      - "rabbitmq"
    hostname: reminder